export { createDeck, shuffleDeck, reshuffleDiscardIntoDeck, reshuffleSideFromDiscard, serializeDeck, serializeDecks, cardToIdentity } from './deck.js';
export type { CardIdentity } from './deck.js';
export { canPlayCard, getPlayableCards, isValidWildDrawFour, canRespondToDrawStack, isExactJumpInMatch } from './validation.js';
export { getNextPlayerIndex, reverseDirection } from './turn.js';
export { dealCards, handleFirstDiscard, initializeGame, initializeNextRound } from './setup.js';
export type { DealResult, FirstCardEffect, FirstDiscardResult } from './setup.js';
export { calculateRoundScore, calculateRoundScores } from './scoring.js';
export { applyAction } from './game-engine.js';
export { applyActionWithHouseRules } from './house-rules-engine.js';
export type { HouseRulePlugin, RuleMetadata, RuleContext, PreCheckResult } from './house-rule-types.js';
export { buildRuleContext } from './house-rule-helpers.js';
export { getAllRuleMetadata } from './house-rule-registry.js';
export { PRE_CHECK_PLUGINS, POST_PROCESS_PLUGINS } from './rules/index.js';
export { chooseAutopilotAction, chooseAutopilotJumpInAction } from './autopilot-strategy.js';
export { HOUSE_RULE_DESCRIPTIONS } from './rule-descriptions.js';
