import type { HouseRules } from '../types/house-rules';

export const HOUSE_RULE_DESCRIPTIONS: Record<keyof HouseRules, string> = {
  stackDrawTwo: '被 +2 时可用 +2 叠加，累计罚牌转给下家',
  stackDrawFour: '被 +4 时可用 +4 叠加，累计罚牌转给下家',
  crossStack: '可以用 +4 应对 +2（或反之），跨类型叠加',
  reverseDeflectDrawTwo: '被 +2 时可出 Reverse 反弹给上家',
  reverseDeflectDrawFour: '被 +4 时可出 Reverse 反弹给上家',
  skipDeflect: '被 +2/+4 时可出 Skip 转移给下家',
  zeroRotateHands: '打出 0 时所有人按方向传递手牌',
  sevenSwapHands: '打出 7 时选择一名玩家交换手牌',
  jumpIn: '持有与弃牌堆顶牌完全相同的牌时，可不等轮次直接出牌',
  multiplePlaySameNumber: '相同数字不同颜色的牌可一次全部打出',
  wildFirstTurn: '第一回合可以出万能牌',
  drawUntilPlayable: '无牌可出时必须一直摸到能出的牌为止',
  forcedPlayAfterDraw: '摸到能出的牌时必须立即打出',
  handLimit: '手牌上限，超过后不能摸牌（null 为无限制）',
  forcedPlay: '有能出的牌就必须出，不能选择摸牌',
  handRevealThreshold: '手牌少于此数量时向所有人公开（null 为关闭）',
  unoPenaltyCount: '不喊 UNO 被抓时罚摸的张数（2/4/6）',
  strictUnoCall: '严格 UNO 规则，必须在出倒数第二张牌时喊',
  misplayPenalty: '出非法牌时罚摸 1 张',
  deathDraw: '无牌可出时必须不停摸牌直到能出',
  fastMode: '快速模式，回合时间限制减半',
  noHints: '关闭可出牌提示',
  elimination: '每轮结束时手牌最多的玩家被淘汰',
  blitzTimeLimit: '闪电战模式，整局游戏总时间限制（null 为关闭）',
  revengeMode: '反击 +2/+4 时罚牌数翻倍',
  silentUno: '取消 UNO 喊话机制',
  teamMode: '团队模式，偶数玩家时对面座位是队友',
  noFunctionCardFinish: '最后一张牌不能是功能牌（Skip/Reverse/+2）',
  noWildFinish: '最后一张牌不能是万能牌（Wild/+4）',
  doubleScore: '赢家得分翻倍',
  noChallengeWildFour: '关闭 +4 质疑机制，必须直接接受',
  blindDraw: '暗牌模式，摸牌后不显示牌面',
  bombCard: '炸弹牌，相同数字 4 张可一次打出清除',
  shuffleSeats: '每轮开始时随机打乱座位顺序',
};
